[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "python -m src.presentation.bot.main --profile pandas"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
