apiVersion: apps/v1
kind: Deployment
metadata:
  name: dask-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dask-operator
  template:
    metadata:
      labels:
        app: dask-operator
    spec:
      serviceAccountName: dask-operator-dask-kubernetes-operator  # TODO: добавить в README инструкцию по созданию dask-operator
      containers:
        - name: operator
          image: ghcr.io/dask/dask-kubernetes-operator:latest
