apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../base/job

patches:
  - target:
      group: batch
      version: v1
      kind: Job
      name: dcp-pipeline-job
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/image
        value: ghcr.io/skerter/distributed-churn-prediction:make-k8s-pipeline-v1
      - op: replace
        path: /spec/template/spec/containers/0/imagePullPolicy
        value: Always