runtime:
  mode: "dask_k8s"

paths:
  data_source: "/mnt/dcp/data/source"
  data_processed: "/mnt/dcp/data/processed"
  models: "/mnt/dcp/models"
  logs: "/mnt/dcp/logs"
  notebooks: "/mnt/dcp/notebooks"

dask:
  scheduler_address: "tcp://localhost:8786"